
core:
  extraEnvVars:
    - name: CONFIG_OVERWRITE_JSON
      value: |
        {
          "auth_mode": "oidc_auth",
          "oidc_name": "KUBAUTH",
          "oidc_endpoint": "https://kubauth.ingress.kubo6.mbp",
          "oidc_groups_claim": "groups",
          "oidc_admin_group": "harbor-admins",
          "oidc_client_id": "harbor",
          "oidc_client_secret": "harbor123",
          "oidc_scope": "openid,email,profile,offline_access,groups",
          "oidc_verify_cert": "false",
          "oidc_auto_onboard": "true",
          "oidc_user_claim": "name"
        }
