

ingress:
  host: kubeconfig.ingress.kubo6.mbp

server:
  tls: true
  certificateIssuer: cluster-odp
networkPolicies:
  enabled: true
kubeconfigs:
  default:
    description: Default OIDC client configuration
    cluster:
      apiServerURL: https://127.0.0.1:5452
    context:
      name: oidc-kubo6
      namespace:  # Left blank. Will allow default context for users
    oidc:
      issuerURL: https://kubauth.ingress.kubo6.mbp
      issuerCaSecretName: certs-bundle
      issuerCaName: ca.crt
      clientId: k8s
      clientSecret: k8s123
